// <auto-generated />
using System;
using Berauto.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Berauto.Backend.Migrations
{
    [DbContext(typeof(CarRentalDbContext))]
    [Migration("20260513120000_InitBerautoState")]
    partial class InitBerautoState
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Berauto.Models.Car", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Brand")
                    .IsRequired()
                    .HasMaxLength(15)
                    .HasColumnType("nvarchar(15)");

                b.Property<int>("Fee")
                    .HasColumnType("int");

                b.Property<int>("FuelId")
                    .HasColumnType("int");

                b.Property<bool>("IsRentable")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<int>("Mileage")
                    .HasColumnType("int");

                b.Property<string>("Model")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("RegNum")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("nvarchar(10)");

                b.Property<int>("StatusId")
                    .HasColumnType("int");

                b.HasKey("Id")
                    .HasName("PK__Cars__3214EC0747D9C496");

                b.HasIndex(new[] { "RegNum" }, "UQ__Cars__34C6A0A69870A7BF")
                    .IsUnique();

                b.ToTable("Cars");
            });

            modelBuilder.Entity("Berauto.Models.CarStatus", b =>
            {
                b.Property<int>("Id")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.HasKey("Id")
                    .HasName("PK__CarStatu__3214EC079E7141F3");

                b.ToTable("CarStatus", (string)null);
            });

            modelBuilder.Entity("Berauto.Models.Fuel", b =>
            {
                b.Property<int>("Id")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.HasKey("Id")
                    .HasName("PK__Fuel__3214EC071FF1B4E1");

                b.ToTable("Fuel", (string)null);
            });

            modelBuilder.Entity("Berauto.Models.Rental", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("CarId")
                    .HasColumnType("int");

                b.Property<string>("Condition")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<DateTime?>("HandoverDate")
                    .HasColumnType("datetime");

                b.Property<DateTime>("PlannedEnd")
                    .HasColumnType("datetime");

                b.Property<DateTime>("PlannedStart")
                    .HasColumnType("datetime");

                b.Property<DateTime?>("RequestDate")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                b.Property<DateTime?>("ReturnDate")
                    .HasColumnType("datetime");

                b.Property<int?>("ReturnMileage")
                    .HasColumnType("int");

                b.Property<int>("StatusId")
                    .HasColumnType("int");

                b.Property<int?>("TotalCost")
                    .HasColumnType("int");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("Id")
                    .HasName("PK__Rentals__3214EC0749B7546D");

                b.HasIndex("CarId");

                b.HasIndex("StatusId");

                b.HasIndex("UserId");

                b.ToTable("Rentals");
            });

            modelBuilder.Entity("Berauto.Models.RentalStatus", b =>
            {
                b.Property<int>("Id")
                    .HasColumnType("int");

                b.Property<string>("StatusName")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.HasKey("Id")
                    .HasName("PK__RentalSt__3214EC071B70ECB1");

                b.ToTable("RentalStatus", (string)null);
            });

            modelBuilder.Entity("Berauto.Models.Role", b =>
            {
                b.Property<int>("Id")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.HasKey("Id")
                    .HasName("PK__Roles__3214EC079F686474");

                b.ToTable("Roles");
            });

            modelBuilder.Entity("Berauto.Models.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Address")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("DrivingLicence")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("Phone")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<int>("RoleId")
                    .HasColumnType("int");

                b.HasKey("Id")
                    .HasName("PK__Users__3214EC07F3940CC2");

                b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053463D6C556")
                    .IsUnique();

                b.HasIndex("RoleId");

                b.ToTable("Users");
            });

            modelBuilder.Entity("Berauto.Models.Car", b =>
            {
                b.HasOne("Berauto.Models.Fuel", "Fuel")
                    .WithMany("Cars")
                    .HasForeignKey("FuelId")
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .IsRequired()
                    .HasConstraintName("FK_Cars_Fuel");

                b.HasOne("Berauto.Models.CarStatus", "Status")
                    .WithMany("Cars")
                    .HasForeignKey("StatusId")
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .IsRequired()
                    .HasConstraintName("FK_Cars_CarStatus");

                b.Navigation("Fuel");

                b.Navigation("Status");
            });

            modelBuilder.Entity("Berauto.Models.Rental", b =>
            {
                b.HasOne("Berauto.Models.Car", "Car")
                    .WithMany("Rentals")
                    .HasForeignKey("CarId")
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .IsRequired()
                    .HasConstraintName("FK_Rentals_Cars");

                b.HasOne("Berauto.Models.RentalStatus", "Status")
                    .WithMany("Rentals")
                    .HasForeignKey("StatusId")
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .IsRequired()
                    .HasConstraintName("FK_Rentals_Status");

                b.HasOne("Berauto.Models.User", "User")
                    .WithMany("Rentals")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .IsRequired()
                    .HasConstraintName("FK_Rentals_Users");

                b.Navigation("Car");

                b.Navigation("Status");

                b.Navigation("User");
            });

            modelBuilder.Entity("Berauto.Models.User", b =>
            {
                b.HasOne("Berauto.Models.Role", "Role")
                    .WithMany("Users")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .IsRequired()
                    .HasConstraintName("FK_Users_Roles");

                b.Navigation("Role");
            });

            modelBuilder.Entity("Berauto.Models.Car", b =>
            {
                b.Navigation("Rentals");
            });

            modelBuilder.Entity("Berauto.Models.CarStatus", b =>
            {
                b.Navigation("Cars");
            });

            modelBuilder.Entity("Berauto.Models.Fuel", b =>
            {
                b.Navigation("Cars");
            });

            modelBuilder.Entity("Berauto.Models.RentalStatus", b =>
            {
                b.Navigation("Rentals");
            });

            modelBuilder.Entity("Berauto.Models.Role", b =>
            {
                b.Navigation("Users");
            });

            modelBuilder.Entity("Berauto.Models.User", b =>
            {
                b.Navigation("Rentals");
            });
#pragma warning restore 612, 618
        }
    }
}
